### ISSUE TITLE
Could not bank when player had hot dice and all dice were in row2. 

### ISSUE THREAD

**Issue by timjancic** [noahapplegate/Farkle#3]

**Comment by timjancic** [comment]
No notification is sent to the player either which is strange.

**Comment by noahapplegate** [comment]
Should the player be able to bank and end their turn if they get hot dice? Currently the player is never able to bank on hot dice due to the bank button being disabled on line 556.

![Screenshot from 2021-11-22 14-46-01](https://user-images.githubusercontent.com/32722387/142946302-dd6603dd-852b-4f86-9d38-69290cd660d4.png)
---------------------------------------------------------------------


I haven't been able to replicate the notification issue. Can you grab a screen shot?

**Hot dice where all dice are in row 2 w/ notification**

![Screenshot from 2021-11-22 14-28-15](https://user-images.githubusercontent.com/32722387/142945169-f9607386-c1bc-4d30-96bf-f9400f762fa4.png)


![Screenshot from 2021-11-22 14-32-18](https://user-images.githubusercontent.com/32722387/142945198-3c48a550-80f3-47cf-9f49-74304e67cc41.png)

**Comment by timjancic** [comment]
Yep looks like I made a mistake about how hot dice work and line 556 should not be there, I will upload with the fix
